In [1]:
import numpy as np
import scipy as sp

In [2]:
def distance(x,y):
    d = np.linalg.norm(x-y)
    return d

In [8]:
def gravity_center(list_pts):
    return list_pts.sum(axis=0)/list_pts.shape[0]

In [31]:
def rand(list_pts,k):
    elts = np.random.choice(list_pts.shape[0], k , replace=False)
    return list_pts[elts,:]

In [32]:
pts = np.random.rand(10,3)

In [33]:
pts

array([[0.68590957, 0.48532807, 0.73444688],
       [0.98173631, 0.15517569, 0.71819218],
       [0.78383023, 0.63338171, 0.04533069],
       [0.13233963, 0.66417302, 0.84769924],
       [0.41486473, 0.98230878, 0.58620108],
       [0.50453356, 0.42198057, 0.18023957],
       [0.70875088, 0.14948117, 0.31242988],
       [0.21489467, 0.9852987 , 0.98934082],
       [0.63465971, 0.82443455, 0.16857342],
       [0.89397856, 0.15373306, 0.60863204]])

In [34]:
distance(pts[1,1],pts[5,2])

0.025063881741647198

In [35]:
gravity_center(pts)

array([0.59554979, 0.54552953, 0.51910858])

In [36]:
rand(pts,5)

array([[0.41486473, 0.98230878, 0.58620108],
       [0.13233963, 0.66417302, 0.84769924],
       [0.21489467, 0.9852987 , 0.98934082],
       [0.63465971, 0.82443455, 0.16857342],
       [0.89397856, 0.15373306, 0.60863204]])

### Implement KMeans

In [38]:
X = np.random.rand(100,5)
k = 2

centroids = rand